os: linux            # linux, osx (custom installation commands required for python),  windows (no python support yet as at 20190114)
language: python

install:
    #- pip install -r requirements.txt
    - pip install .

script:
    - python -c "import pytest" && pytest -v . || python ./tests/test_Foo.py 

matrix:
    include:
        - python: "2.6"
        - python: "2.7"
        - python: "3.2" # pytest does not support this version
        - python: "3.3" # pytest does not support this version
        - python: "3.4"
        - python: "3.5"
        - python: "3.6"
        - python: "3.7-dev" # 3.7 not available yet (last checked 20190114)
          
        - os: osx   # seems to come with python and python3 but it's less clear how to take control of precise version---maybe via `brew install pyenv-virtualenv` (which takes a loooong time) plus (unknown) extra steps
          language: generic
          install: python2 -m pip install pytest .
          script:  python2 -m pytest -v .
          
        - os: osx
          language: generic
          install: python3 -m pip install pytest .
          script:  python3 -m pytest -v .
