os: linux            # linux, osx (custom installation commands required for python),  windows (no python support yet as at 20190114)
language: python

install:
    #- pip install -r requirements.txt
    - pip install .

script:
    - python -c "import pytest" && pytest -v . || python ./tests/test_Foo.py 

matrix:
    include:
        #- python: "2.6"
        #- python: "2.7"
        - python: "3.2" # pytest does not support this version
        #- python: "3.3" # pytest does not support this version
        #- python: "3.4"
        #- python: "3.5"
        #- python: "3.6"
        - python: "3.7-dev" # 3.7 not available yet (last checked 20190114)
          
        - os: osx
          language: generic
          install:
            - brew install pyenv-virtualenv
            - pip install pytest
            - pip install .
