language: python

os:
    - linux
    - osx
    - windows
    
# pip install -r requirements.txt
install:
    - pip install .

script:
    - python -c "import pytest" && pytest -v . || python ./tests/test_Foo.py 
