os: linux            # linux, osx (custom installation commands required for python),  windows (no python support yet as at 20190114)
language: python
env: PYTHON=python
install:
    - $PYTHON -m pip install --upgrade pip
    - $PYTHON -m pip install pytest
    - $PYTHON -m pip install .
    #- $PYTHON -m pip install -r requirements.txt

script:
    - $PYTHON -m pytest -v .

matrix:
    include:
        #- python: "2.6"  # update 20200807: Travis no longer supports this
        - python: "2.7"
        #- python: "3.2" # pytest does not support this version; update 20200807: Travis no longer supports this either
        #- python: "3.3" # pytest does not support this version; update 20200807: Travis no longer supports this either
        - python: "3.4"
        - python: "3.5"
        - python: "3.6"
        - python: "3.7"
        - python: "3.8"
        - python: "3.9-dev" # no 3.9 available on Travis as at 20200807
          
        - name: "Python 2.x on macOS"
          os: osx   # seems to come with python and python3 but it's less clear how to take control of precise version---maybe via `brew install pyenv-virtualenv` (which takes a loooong time) plus (unknown) extra steps
          language: generic
          env: PYTHON=python2
          
        - name: "Python 3.x on macOS"
          os: osx
          language: generic
          env: PYTHON=python3

        - name: "Python 2.7 on Windows"
          os: windows
          language: shell
          before_install:
              - choco install python --version=2.7.11
          env:
              - PATH=/c/Python27:/c/Python27/Scripts:$PATH      # note that the path must change according to the Python version
              - PYTHON=python

        - name: "Python 3.8 on Windows"
          os: windows
          language: shell
          before_install:
              - choco install python --version=3.8
          env:
              - PATH=/c/Python38:/c/Python38/Scripts:$PATH      # note that the path must change according to the Python version
              - PYTHON=python

        - name: "Python 3.8 on 32-bit Windows"
          os: windows
          arch: x86
          language: shell
          before_install:
              - choco install python --version=3.8
          env:
              - PATH=/c/Python38:/c/Python38/Scripts:$PATH      # note that the path must change according to the Python version
              - PYTHON=python
